id: /subscriptions/e4ea9fb0-d0b9-459b-8fe5-384d2054ae97/resourceGroups/shopping-rg/providers/Microsoft.App/containerapps/shopping-backend
identity:
  type: None
location: East US
name: shopping-backend
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    identitySettings: []
    ingress:
      additionalPortMappings: null
      allowInsecure: false
      clientCertificateMode: null
      corsPolicy: null
      customDomains: null
      exposedPort: 0
      external: true
      fqdn: shopping-backend.greengrass-56c2de65.eastus.azurecontainerapps.io
      ipSecurityRestrictions: null
      stickySessions: null
      targetPort: 7070
      traffic:
      - latestRevision: true
        weight: 100
      transport: Auto
    maxInactiveRevisions: 100
    registries:
    - identity: ''
      passwordSecretRef: shoppingregistry9946azurecrio-shoppingregistry9946
      server: shoppingregistry9946.azurecr.io
      username: shoppingregistry9946
    runtime: null
    secrets:
    - name: shoppingregistry9946azurecrio-shoppingregistry9946
    - name: db-password
    - name: redis-password
    service: null
  customDomainVerificationId: 9BE72626CB9EE2A1066E21C6A3D1D8E68D52911875CA74A40A8258878A3DB9BB
  delegatedIdentities: []
  environmentId: /subscriptions/e4ea9fb0-d0b9-459b-8fe5-384d2054ae97/resourceGroups/shopping-rg/providers/Microsoft.App/managedEnvironments/shopping-env
  eventStreamEndpoint: https://eastus.azurecontainerapps.dev/subscriptions/e4ea9fb0-d0b9-459b-8fe5-384d2054ae97/resourceGroups/shopping-rg/containerApps/shopping-backend/eventstream
  latestReadyRevisionName: shopping-backend--2t1lvwu
  latestRevisionFqdn: shopping-backend--0000015.greengrass-56c2de65.eastus.azurecontainerapps.io
  latestRevisionName: shopping-backend--0000015
  managedEnvironmentId: /subscriptions/e4ea9fb0-d0b9-459b-8fe5-384d2054ae97/resourceGroups/shopping-rg/providers/Microsoft.App/managedEnvironments/shopping-env
  outboundIpAddresses:
  - 20.127.248.50
  - 20.241.171.30
  - 20.169.229.88
  - 20.169.229.46
  - 20.169.229.29
  - 20.169.229.38
  - 20.169.229.62
  - 20.169.229.109
  - 20.169.229.92
  - 20.169.229.27
  - 20.169.229.51
  - 20.169.229.42
  - 20.241.172.248
  - 48.216.192.198
  - 40.90.243.232
  - 40.90.242.126
  - 135.237.112.47
  - 51.8.74.190
  - 4.157.197.142
  - 172.210.91.191
  - 172.210.90.42
  - 40.90.243.227
  - 40.90.243.72
  - 20.241.172.250
  - 52.234.235.220
  - 57.152.55.92
  - 172.212.36.156
  - 172.210.121.45
  - 172.214.2.208
  - 51.8.15.68
  - 172.210.90.119
  - 134.33.213.81
  - 128.203.83.220
  - 20.241.192.93
  - 20.246.203.138
  - 172.212.121.150
  - 172.171.186.158
  - 52.249.213.152
  - 74.179.213.114
  - 4.246.239.152
  - 4.156.216.65
  - 4.157.231.174
  - 172.171.168.136
  - 20.185.213.14
  - 20.246.203.140
  - 13.82.216.169
  - 13.82.216.172
  - 13.82.216.149
  - 52.170.33.171
  - 20.231.246.122
  - 20.231.246.54
  - 40.121.19.105
  - 40.121.18.246
  - 40.121.18.166
  - 40.121.18.60
  - 40.121.18.21
  - 40.121.18.44
  - 40.121.18.41
  - 40.121.18.248
  - 40.121.18.82
  - 40.121.19.108
  - 20.231.247.19
  - 40.121.19.125
  - 40.121.18.46
  - 40.117.125.130
  - 40.121.18.52
  - 40.121.18.33
  - 40.121.18.238
  - 40.121.19.2
  - 40.121.19.122
  - 40.121.19.19
  - 40.121.18.114
  - 20.231.246.253
  - 40.121.18.255
  - 40.121.18.164
  - 40.117.121.106
  - 40.121.18.27
  - 40.121.18.156
  - 40.121.18.117
  - 40.121.18.197
  - 40.121.18.133
  - 40.121.18.112
  - 40.121.18.106
  - 20.241.227.6
  - 40.121.19.89
  - 40.121.19.83
  - 40.121.18.131
  - 40.121.18.201
  - 40.121.18.170
  - 40.121.18.242
  - 13.92.130.42
  - 40.121.19.42
  - 40.121.18.73
  - 40.121.18.43
  - 20.241.226.169
  - 51.8.12.17
  - 4.156.180.142
  - 20.242.162.124
  - 40.121.19.74
  - 40.121.19.40
  - 40.121.18.62
  - 40.121.18.244
  - 20.83.140.132
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - args:
      - '[''-c'', ''sleep 3600'']'
      command:
      - '[''/bin/sh'']'
      env:
      - name: ALLOWED_ORIGINS
        value: '*'
      - name: SPRING_DATASOURCE_URL
        value: jdbc:mysql://shopping-mysql.internal.greengrass-56c2de65.eastus.azurecontainerapps.io:3306/shopping_app?useSSL=false
      - name: SPRING_DATASOURCE_USERNAME
        value: shopuser
      - name: SPRING_DATASOURCE_PASSWORD
        secretRef: db-password
      - name: SPRING_DATA_REDIS_HOST
        value: shopping-redis.internal.greengrass-56c2de65.eastus.azurecontainerapps.io
      - name: SPRING_DATA_REDIS_PORT
        value: '6379'
      - name: SPRING_DATA_REDIS_PASSWORD
        secretRef: redis-password
      - name: spring.data.redis.ssl.enabled
        value: 'false'
      - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: localhost:9092
      - name: spring.kafka.listener.auto-startup
        value: 'false'
      - name: JASYPT_ENCRYPTOR_PASSWORD
        value: commerce
      image: shoppingregistry9946.azurecr.io/backend:latest
      name: shopping-backend
      resources:
        cpu: 1.0
        ephemeralStorage: 4Gi
        memory: 2Gi
    initContainers: null
    revisionSuffix: ''
    scale:
      cooldownPeriod: 300
      maxReplicas: 1
      minReplicas: 1
      pollingInterval: 30
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes: null
  workloadProfileName: Consumption
resourceGroup: shopping-rg
systemData:
  createdAt: '2026-01-23T16:42:03.6318058'
  createdBy: wang.yu-e@northeastern.edu
  createdByType: User
  lastModifiedAt: '2026-01-23T21:08:00.8302628'
  lastModifiedBy: wang.yu-e@northeastern.edu
  lastModifiedByType: User
type: Microsoft.App/containerApps
